### ISSUE TITLE
Access Logic

### ISSUE THREAD

**Issue by jared2710** [cos301-2019-se/Smart-NFC-Card-Applications#81]
Add two functions to a new endpoint accessLogic:
getAllCompanyBuildingRoomsGroups
checkAccess

**Comment by jared2710** [comment]
Maybe call the endpoint access, like:
access/checkAccess

**Comment by DuncanV** [comment]
The function names are as follows:

getAccess
getAllCompanyBuildingRooms

and are accessed via /access/getAccess for e.g
