### ISSUE TITLE
Add CRUD for New Tables

### ISSUE THREAD

**Issue by savvas17** [cos301-2019-se/Smart-NFC-Card-Applications#87]
transactions table: id wid amount npp transactionTime description
nfcPaymentPoints: nppId buildingId description

**Comment by jared2710** [comment]
Savvas I added the tables and added the inserts and gets, pushed to branch #87_CrudControllerPayment, check the new tables out on SAVVAS JARED WORKING, add those to your db, and then you can get cracking on those updates and deletes - it didn't take me long at all so I doubt it will for you either!
